name: Update Articles Every Hour

on:
  schedule:
    - cron: "0 * * * *" # every hour, on the hour
  workflow_dispatch: # allows manual run from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install httpx selectolax

      - name: Run script
        run: python articles.py

      - name: Commit and push if changed
        run: |
          git config user.name "TweetingCynical"
          git config user.email "jon@exce-ed.com"
          git add assets/js/articles.json
          git diff --cached --quiet || git commit -m "Auto-update articles.json"
          git push
